### ISSUE TITLE
Add support for .SetActive() to DropdownLink

### ISSUE THREAD

**Issue by peter3** [somedave/FluentBootstrap#22]
Using .AddCss("active") as a work-around sets the css on the `<a>` tag instead of on the parent `<li>` where it should be.

**Comment by somedave** [comment]
Is "active" a valid class name for dropdown links? It's not documented in the Bootstrap docs:
http://getbootstrap.com/components/#dropdowns

Is it one of those things that works, but isn't officially supported? If so, I've got no problem adding it - I'll just need to create a little extra testing to make sure that as an undocumented feature it doesn't break in the future...

**Comment by somedave** [comment]
This is now fixed in the development branch. It'll go out with the next NuGet push in a few days when I bump to Bootstrap 3.3.4.
