### ISSUE TITLE
AddStaticClass is ambiguous between FormExtensions and MvcFormExtensions

### ISSUE THREAD

**Issue by fairking** [somedave/FluentBootstrap#71]
I receive an error in following razor:
`@(Html.Bootstrap()
                                .FormGroup()
                                .AddChild(Html.Bootstrap().ControlLabel(x => x.H_TestDisplayStringValue).SetMd(4))
                                .AddChild(Html.Bootstrap().FormControl().AddStaticClass().SetMd(7)
                                    .AddContent(Html.DisplayFor(x => x.H_TestDisplayStringValue))
                                )
                                .AddChild(Html.Bootstrap().BadgeTooltip("Test Display").SetPullRight())
                            )`

Message:
> The call is ambiguous between the following methods or properties: 'FluentBootstrap.FormExtensions.AddStaticClass<TConfig>(FluentBootstrap.ComponentBuilder<TConfig, FluentBootstrap.Forms.FormControl>, bool)' and 'FluentBootstrap.MvcFormExtensions.AddStaticClass<TModel, TFormControlFor>(FluentBootstrap.ComponentBuilder<FluentBootstrap.Mvc.MvcBootstrapConfig<TModel>, TFormControlFor>, bool)'

How can resolve the conflict of namespaces?

Thanks.

**Comment by daveaglick** [comment]
Try specifying the generic type parameters of the `AddStaticClass()` method like this (where `ViewModel` is whatever your model type for the view is):
```
@(Html.Bootstrap() .FormGroup() .AddChild(Html.Bootstrap().ControlLabel(x => x.H_TestDisplayStringValue).SetMd(4)) .AddChild(Html.Bootstrap().FormControl().AddStaticClass<MvcBootstrapConfig<ViewModel>>().SetMd(7) .AddContent(Html.DisplayFor(x => x.H_TestDisplayStringValue)) ) .AddChild(Html.Bootstrap().BadgeTooltip("Test Display").SetPullRight()) )
```

Getting rid of these ambiguous extension method resolution errors was a big problem a while back. I was able to squash almost all of them, but in complicated cases like this you sometimes have to give it a little hint.

Please reopen this issue if it looks like this suggestion doesn't work for you.
